### ISSUE TITLE
Add value checking on PrintType

### ISSUE THREAD

**Issue by dswright1990** [SPDX-Git/SPDX-Git-Scanner#47]
If the user sets PrintType in config.txt to a garbage string you could easily catch it with an if statement and set it to a default value.

**Comment by DanPatten** [comment]
Enhancement tag was added as this is a small addition to prevent user error.

**Comment by jvosik** [comment]
I would rather not do this one. Validating the print type would involve mirroring DoSOCS checks, when I would rather pass it to DoSOCS (as we are) and let it handle the bad types. The reason I would prefer this is because if DoSOCS adds a print type in the future (say, csv), then GitSPDX would have to be updated to remain compatible. If we don't do this enhancement, however, DoSOCS is able to add/remove print types without it affecting this script.
