### ISSUE TITLE
add option for seperate DoSocs path

### ISSUE THREAD

**Issue by plato360** [SPDX-Git/SPDX-Git-Scanner#49]
while we can change the fossology path and options for the database, it'd also be nice if the user could set a path for DoSocs if it's already installed.  The way it's currently setup, if the user has already been using DoSocs for another purpose, you force them to set up a second copy for the Git-Scanner

**Comment by DanPatten** [comment]
Not sure about this, for are install process we assume you are not using doSOCS and it downloads and installs it for you so you literally have nothing to do. Already having doSOCS setup in another location is not really an issue either because doSOCs does not need to be installed to run. Since both can connect to the same MySQL database, you can point it to the existing instance.

**Comment by DanPatten** [comment]
Not correcting, as you can use a central SPDX database and doSOCS will be automatically configured.

**Comment by plato360** [comment]
but if a user is using multiple programs with doSOCS dependencies wouldn't it be nicer to have one copy of doSOCS than 6?
